name: Bicep Standard CI
description: |
  This action builds Bicep templates and uploads the artifacts.

runs:
  using: composite
  steps:
      - name: Update Packages
        shell: bash
        run: |
          echo "✅ Updating packages..."
          # Simulate package update
          sudo apt-get update
          echo "✅ Packages updated successfully"

      - name: Setup Git identity
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Debug trigger information
        shell: bash
        run: |
          echo "🐛 Debug Information:"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "SHA: ${{ github.sha }}"

      - name: Build Accelerator Bicep
        shell: bash
        run: |
          echo "✅ Building Bicep templates..."
          mkdir -p ./artifacts
          
          # Check if Azure CLI is available
          if command -v az &> /dev/null; then
            az bicep build --file ./infra/main.bicep --outdir ./artifacts
            echo "✅ Bicep build completed"
          else
            echo "⚠️ Azure CLI not available, creating placeholder artifacts"
            echo "Bicep build would be executed here" > ./artifacts/placeholder.txt
          fi