# =============================================================================
# File: action.yml (bicep-standard-ci)
# Purpose: Composite action for building and uploading Bicep artifacts
# Description: Compiles Bicep templates to ARM and uploads versioned artifacts
# =============================================================================

name: Bicep Standard CI
description: |
  Builds Bicep templates, compiles them to ARM templates, and uploads
  versioned artifacts for deployment or release.

inputs:
  branch_name:
    description: "The name of the branch being built"
    required: true
  new_version:
    description: "The semantic version being built (e.g., v1.2.3)"
    required: true
  should_publish:
    description: "Whether the build artifacts should be published to a release"
    required: true

runs:
  using: composite

  steps:
    - name: Build Bicep Templates
      shell: bash
      run: |
        echo "::group::Building Bicep templates"
        echo "✅ Building Bicep templates..."
        mkdir -p ./artifacts

        # Check if Azure CLI is available
        if command -v az &> /dev/null; then
          az bicep build --file ./infra/main.bicep --outdir ./artifacts
          echo "✅ Bicep build completed successfully"
        else
          echo "::error::Azure CLI not available - cannot build Bicep templates"
          exit 1
        fi
        echo "::endgroup::"

    - name: Upload Versioned Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: artifacts-${{ inputs.new_version }}
        path: ./artifacts
        compression-level: 6
        if-no-files-found: error
        retention-days: 30

    - name: Generate Artifact Summary
      shell: bash
      run: |
        branch_name="${{ inputs.branch_name }}"
        version="${{ inputs.new_version }}"
        should_publish="${{ inputs.should_publish }}"

        echo "## 📦 Build Artifacts Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Version | \`$version\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Branch | \`$branch_name\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Tag Created | ✅ |" >> $GITHUB_STEP_SUMMARY
        echo "| Artifacts Uploaded | ✅ |" >> $GITHUB_STEP_SUMMARY
        echo "| Publish Release | $should_publish |" >> $GITHUB_STEP_SUMMARY

        if [[ "$should_publish" == "false" ]]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> **Note:** This is a development build from a non-main branch." >> $GITHUB_STEP_SUMMARY
          echo "> Tag and artifacts are created for tracking, but no GitHub release will be published." >> $GITHUB_STEP_SUMMARY
        fi
