# yaml-language-server: $schema=./network.schema.json

create: true
name: devexp
addressPrefixes:
  - 10.0.0.0/16
subnets:
  - name: devexp-subnet
    properties:
      addressPrefix: 10.0.1.0/24
tags:
  environment: dev
  division: Platforms
  team: DevExP
  project: DevExP-DevBox
  costCenter: IT
  owner: Evilazaro
  resources: Network
