name: Dev Box Accelerator - Deployment
trigger: none

pool:
  vmImage: ubuntu-latest
  name: linuxPool

steps:
  # If you can't install above task in your organization, you can comment it and uncomment below task to install azd
  - task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update && sudo apt-get upgrade -y
        curl -fsSL https://aka.ms/install-azd.sh | sudo bash

  # azd delegate auth to az to use service connection with AzureCLI@2
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.
  
  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      KEY_VAULT_SECRET: $(KEY_VAULT_SECRET)

