
# yaml-language-server: $schema=./security.schema.json
# -------------------------------------------------------
# Azure Key Vault Configuration
# -------------------------------------------------------
# Purpose: Centralized management of secrets, keys, and certificates for secure access by applications and services in the Contoso development environment.
# This file defines the configuration for an Azure Key Vault resource used for storing sensitive credentials and secrets in the development environment.
#
# References:
# - Microsoft Dev Box accelerator: https://evilazaro.github.io/DevExp-DevBox/docs/configureresources/security/
# - Azure Key Vault documentation: https://learn.microsoft.com/en-us/azure/key-vault/general/basic-concepts
# - Azure Key Vault best practices: https://learn.microsoft.com/en-us/azure/key-vault/general/best-practices

# Top-level flag: Should the Key Vault resource be created?
create: true

# Key Vault configuration block
keyVault:
  # Basic settings
  name: contoso                                 # Globally unique Key Vault name
  description: Development Environment Key Vault # Purpose of this Key Vault
  secretName: gha-token                         # Name of the GitHub Actions token secret

  # Security settings
  enablePurgeProtection: true                   # Prevent permanent deletion of secrets
  enableSoftDelete: true                        # Allow recovery of deleted secrets within retention period
  softDeleteRetentionInDays: 7                  # Retention period for deleted secrets (7-90 days)
  enableRbacAuthorization: true                 # Use Azure RBAC for access control

  # Resource organization tags
  tags:
    environment: dev                            # Deployment environment (dev/test/staging/prod)
    division: Platforms                         # Organizational division
    team: DevExP                                # Owning team
    project: Contoso-DevExp-DevBox              # Associated project
    costCenter: IT                              # Cost center for billing
    owner: Contoso                              # Resource owner
    landingZone: security                       # Azure landing zone classification
    resources: ResourceGroup                    # Resource grouping identifier