trigger:
- none

pr:
- none

variables:
  location: "westus3"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"

jobs:

- job: Build_and_Deploy
  displayName: 'Build and Deploy Microsoft DevBox Resources to Azure'
  pool:
    name: Linux
  steps:
  - checkout: self
  - task: Bash@3
    displayName: 'Update Packages and Install Bicep'
    inputs:
      targetType: 'inline'
      script: |
        az bicep upgrade
  
  - task: Bash@3
    displayName: 'Build Dev Box Management Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/management/logAnalytics/deploy.bicep --outdir ./bicepArtifacts

  - task: Bash@3
    displayName: 'Build Dev Box Network Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outdir ./bicepArtifacts

  - task: Bash@3
    displayName: 'Build Dev Box DevCenter Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outdir ./bicepArtifacts
  
  - task: Bash@3
    displayName: 'Grant permissions to the Script'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

  - task: AzureCLI@2
    displayName: 'Deploy Landing Zone Resources'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ./src/deploy/bicep/bash/deployResourcesOrganization.sh $(devBoxResourceGroupName) $(networkResourceGroupName) $(managementResourceGroupName) $(location)

  - task: AzureCLI@2
    displayName: 'Deploy Dev Box Management Resources to Azure'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(managementResourceGroupName) \
          --template-file ./src/deploy/bicep/management/logAnalytics/deploy.bicep \
          --parameters solutionName=$(solutionName) \
          --mode Incremental 
  
  - task: AzureCLI@2
    displayName: 'Deploy Dev Box Network Resources to Azure'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(networkResourceGroupName) \
          --template-file ./src/deploy/bicep/network/deploy.bicep \
          --parameters solutionName=$(solutionName) managementResourceGroupName=$(managementResourceGroupName) \
          --mode Incremental

  - task: AzureCLI@2
    displayName: 'Deploy Dev Box DevCenter Resources to Azure'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(devBoxResourceGroupName) \
          --template-file ./src/deploy/bicep/devBox/deploy.bicep \
          --parameters solutionName=$(solutionName) managementResourceGroupName=$(managementResourceGroupName) \
          --mode Incremental