trigger:
- none

pr:
- none

variables:
  location: "westus3"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"

jobs:

- job: Deploy
  displayName: 'Deploy Resources'
  pool:
    name: Linux
  steps:
  - checkout: self
  - task: Bash@3
    displayName: 'Update Packages and Install Bicep'
    inputs:
      targetType: 'inline'
      script: |
        az bicep upgrade
  
  - task: Bash@3
    displayName: 'Compile Management Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build ./src/deploy/bicep/management/logAnalytics/deploy.bicep
  
  - task: Bash@3
    displayName: 'Grant permissions to the Script'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

  - task: AzureCLI@2
    displayName: 'Create Azure Resource Groups'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ./src/deploy/bicep/bash/deployResourcesOrganization.sh $(devBoxResourceGroupName) $(networkResourceGroupName) $(managementResourceGroupName) $(location)

  - task: AzureCLI@2
    displayName: 'Deploy Management Resources'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(managementResourceGroupName) \
          --template-file ./src/deploy/bicep/management/logAnalytics/deploy.bicep \
          --parameters solutionName=$(solutionName)