trigger:
- main

variables:
  location: "westus3"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"

jobs:

- job: Build
  displayName: 'Build Microsoft DevBox Bicep Files'
  pool:
    name: Linux
  steps:
  - checkout: self
  - task: Bash@3
    displayName: 'Update Packages and Install Bicep'
    inputs:
      targetType: 'inline'
      script: |
        az bicep upgrade
  
  - task: Bash@3
    displayName: 'Build Dev Box Management Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/management/logAnalytics/deploy.bicep --outfile ./bicepArtifacts/deployManagement.json

  - task: Bash@3
    displayName: 'Build Dev Box Network Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./bicepArtifacts/deployDevBox.json

  - task: Bash@3
    displayName: 'Build Dev Box DevCenter Resources Bicep files'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./bicepArtifacts/deployDevBox.json

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Bicep Artifacts'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/bicepArtifacts'
      ArtifactName: 'bicepArtifacts'