# .github/ISSUE_TEMPLATE/bug.yml
name: '🐞 Bug report'
description: 'Report something that is broken or not working as expected.'
title: 'bug: <short description>'
labels: ['type:bug', 'status:triage']
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail to **reproduce**. If you suspect a security issue, use the Security policy link.

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce.
      placeholder: |
        1. Deploy ...
        2. Configure ...
        3. Run ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / screenshots (redact secrets)
      description:
        Paste logs or error output. Remove tokens, secrets, IDs if sensitive.
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide environment details to reproduce.
      placeholder: |
        - OS:
        - Shell:
        - Azure Region:
        - Subscription type:
        - Dev Center / Dev Box details:
        - Module/version/commit:
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S0 - outage / data loss / security impact
        - S1 - major functionality broken
        - S2 - minor functionality broken
        - S3 - cosmetic / non-blocking
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Triage checks
      options:
        - label: I verified this is not a duplicate issue
          required: true
        - label: I removed/obfuscated secrets from logs
          required: true
        - label: I can reproduce this consistently
          required: false
