# yaml-language-server: $schema=./azureResources.shema.json

workload:
  create: true
  name: workload_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

security:
  create: true
  name: security_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

monitoring:
  create: true
  name: monitoring_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

connectivity:
  create: true
  name: connectivity_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup
