# yaml-language-server: $schema=./azureResources.shema.json

  
workload:
  create: true
  name: DevExP-Workload-prod
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: DevExP-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup
