# yaml-language-server: $schema=./azureResources.shema.json

workload:
  create: false
  name: kac_digitaloffice_devboxs_eus_dev_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

security:
  create: false
  name: kac_digitaloffice_devboxs_eus_dev_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

monitoring:
  create: false
  name: kac_digitaloffice_devboxs_eus_dev_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup

connectivity:
  create: false
  name: kac_digitaloffice_devbox_network_eus_dev_rg
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: Contoso-DevExp-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup
