# yaml-language-server: $schema=./azureResources.shema.json

connectivity: 
  create: true 
  name: DevExP-Connectivity
  description: connectivity
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: DevExP-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Connectivity
    resources: ResourceGroup

compute:
  create: true
  name: DevExP-Compute
  description: compute
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: DevExP-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Identity
    resources: ResourceGroup

management:
  create: true
  name: DevExP-Management
  logAnalyticsName: loganalytics-dev
  description: management
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: DevExP-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Management
    resources: ResourceGroup
    
workload:
  create: true
  name: DevExP-Workload
  description: prodExp
  tags:
    environment: dev
    division: Platforms
    team: DevExP
    project: DevExP-DevBox
    costCenter: IT
    owner: Evilazaro
    landingZone: Workload
    resources: ResourceGroup
