# yaml-language-server: $schema=./devcenter.schema.json

name: DevExP-devcenter
location: eastus2
catalogItemSyncEnableStatus: Enabled
microsoftHostedNetworkEnableStatus: Enabled
installAzureMonitorAgentEnableStatus: Enabled
identity:
  type: SystemAssigned
catalogs:
  - name: customTasks
    type: gitHub
    uri: https://github.com/Evilazaro/DevExP-DevBox.git
    branch: main
    path: .configuration/devcenter/tasks
environmentTypes:
  - name: dev
projects:
  - name: identityProvider
    description: identityProvider
    environmentTypes:
      - name: dev
        deploymentTargetId: "00000000-0000-0000-0000-000000000000"
    catalogs:
      - name: environments
        type: gitHub
        uri: https://github.com/Evilazaro/identityProvider.git
        branch: main
        path: .configuration/devcenter/environments/dev