# yaml-language-server: $schema=./devcenter.schema.json

name: "devexp-devcenter"
location: "eastus2"
catalogItemSyncEnableStatus: "Enabled"
microsoftHostedNetworkEnableStatus: "Enabled"
installAzureMonitorAgentEnableStatus: "Enabled"

identity:
  type: "SystemAssigned"
  usergroup:
    id: "87d1a1df-38cf-416f-b5f7-a5e115de66ad"
    name: "devexp-devbox"
  
  roleAssignments:
    - name: "Contributor"
      id: "b24988ac-6180-42a0-ab88-20f7382dd24c"
    - name: "DevCenter Dev Box User"
      id: "45d50f46-0b78-4001-a660-4198cbe8cd05"
    - name: "DevCenter Project Admin"
      id: "331c37c6-af14-46d9-b9f4-e1909e1b95a0"
    - name: "Deployment Environments User"
      id: "18e40d4e-8d2e-438d-97e1-9528336e149c"
    - name: "Deployment Environments Reader"
      id: "eb960402-bf75-4cc3-8d68-35b34f960f72"
    - name: "User Access Administrator"
      id: "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9"

catalogs:
  - name: "customTasks"
    type: "gitHub"
    uri: "https://github.com/Evilazaro/DevExP-DevBox.git"
    branch: "main"
    path: ".configuration/devcenter/tasks"

environmentTypes:
  - name: "dev"
    deploymentTargetId: ""
  - name: "staging"
    deploymentTargetId: ""

projects:
  - name: "identityProvider"
    description: "Identity Provider project."

    pools:
      - name: "backend-engineer"
        imageDefinitionName: "identityProvider-backend-engineer"
      - name: "frontend-engineer"
        imageDefinitionName: "identityProvider-frontend-engineer"

    environmentTypes:
      - name: "dev"
        deploymentTargetId: ""
      - name: "staging"
        deploymentTargetId: ""

    catalogs:
      environmentDefinition:
        name: "environments"
        type: "gitHub"
        uri: "https://github.com/Evilazaro/identityProvider.git"
        branch: "main"
        path: ".configuration/devcenter/environments"
      imageDefinition:
        name: "imageDefinitions"
        type: "gitHub"
        uri: "https://github.com/Evilazaro/identityProvider.git"
        branch: "main"
        path: ".configuration/devcenter/imageDefinitions"

    tags:
      environment: "dev"
      division: "Platforms"
      team: "DevExP"
      project: "DevExP-DevBox"
      costCenter: "IT"
      owner: "Evilazaro"
      resources: "Project"

  - name: "eShop"
    description: "eShop project."

    pools:
      - name: "backend-engineer"
        imageDefinitionName: "eShop-backend-engineer"
      - name: "frontend-engineer"
        imageDefinitionName: "eShop-frontend-engineer"

    environmentTypes:
      - name: "dev"
        deploymentTargetId: ""
      - name: "staging"
        deploymentTargetId: ""

    catalogs:
      environmentDefinition:
        name: "environments"
        type: "gitHub"
        uri: "https://github.com/Evilazaro/eShop.git"
        branch: "main"
        path: ".devcenter/environments"
      imageDefinition:
        name: "imageDefinitions"
        type: "gitHub"
        uri: "https://github.com/Evilazaro/eShop.git"
        branch: "main"
        path: ".devcenter/imageDefinitions"

    tags:
      environment: "dev"
      division: "Platforms"
      team: "DevExP"
      project: "DevExP-DevBox"
      costCenter: "IT"
      owner: "Evilazaro"
      resources: "Project"

tags:
  environment: "dev"
  division: "Platforms"
  team: "DevExP"
  project: "DevExP-DevBox"
  costCenter: "IT"
  owner: "Evilazaro"
  resources: "DevCenter"
