# yaml-language-server: $schema=./devcenter.schema.json

name: devcenter4
location: eastus2
catalogItemSyncEnableStatus: Enabled
microsoftHostedNetworkEnableStatus: Enabled
installAzureMonitorAgentEnableStatus: Enabled

identity:
  type: SystemAssigned

network:
  create: true
  name: DevExP-vNet
  addressPrefixes:
    - 10.0.0.0/16
  subnets:
    - name: identityProvider
      properties:
        addressPrefix: 10.0.1.0/24

catalogs:
  - name: catalog
    type: gitHub
    uri: https://github.com/Evilazaro/IdentityProvider.git
    branch: main
    path: ./path/to/catalog1
    
  - name: catalog2
    type: gitHub
    uri: https://github.com/Evilazaro/IdentityProvider.git
    branch: main
    path: ./path/to/catalog2

environmentTypes:
  - name: dev
  - name: prod

projects:
  - name: project1
    description: Project 1 Description
    catalogs:
      - name: catalog4
        type: gitHub
        uri: https://github.com/Evilazaro/IdentityProvider.git
        branch: main
        path: ./path/to/catalog1
    environmentTypes:
      - name: dev
        identity:
          type: SystemAssigned
        deploymentTargetId: ""
