# yaml-language-server: $schema=./devcenter.schema.json
#
# Microsoft Dev Box accelerator: Dev Center Configuration
# ======================================
#
# Purpose: Defines the Dev Center resource and associated projects for Microsoft Dev Box accelerator.
# This configuration establishes a centralized developer workstation platform with
# role-specific configurations and appropriate access controls.
#
# References:
# - Microsoft Dev Box accelerator: https://evilazaro.github.io/DevExp-DevBox/docs/configureresources/workload/
# - Dev Center documentation: https://learn.microsoft.com/en-us/azure/dev-box/overview-what-is-microsoft-dev-box
# - Azure RBAC roles: https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles

name: "devexp-devcenter"
catalogItemSyncEnableStatus: "Enabled"
microsoftHostedNetworkEnableStatus: "Enabled"
installAzureMonitorAgentEnableStatus: "Enabled"

# Identity configuration for the Dev Center resource
# Defines how the Dev Center authenticates and what permissions it has
identity:
  type: "SystemAssigned"

  # Role assignments section - defines permissions for Dev Center operation
  roleAssignments:
    devCenter:
      - id: "b24988ac-6180-42a0-ab88-20f7382dd24c"
        name: "Contributor"
        scope: "Subscription"
      - id: "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9"
        name: "User Access Administrator"
        scope: "Subscription"
      - id: "4633458b-17de-408a-b874-0445c86b69e6"
        name: "Key Vault Secrets User"
        scope: "ResourceGroup"
      - id: "b86a8fe4-44ce-4948-aee5-eccb2c155cd7"
        name: "Key Vault Secrets Officer"
        scope: "ResourceGroup"

    orgRoleTypes:
      # Dev Manager role - for users who manage Dev Box deployments
      # These users can configure Dev Box definitions but typically don't use Dev Boxes
      - type: DevManager
        azureADGroupId: "5a1d1455-e771-4c19-aa03-fb4a08418f22"
        azureADGroupName: "Platform Engineering Team"

        # RBAC roles assigned to Dev Managers
        azureRBACRoles:
          # DevCenter Project Admin role allows managing project settings
          - name: "DevCenter Project Admin"
            id: "331c37c6-af14-46d9-b9f4-e1909e1b95a0"
            scope: ResourceGroup

# Catalogs section - defines repositories containing Dev Box configurations
# These catalogs provide centralized, version-controlled configuration
# Best practice: Use Git repositories for configuration-as-code approach
catalogs:
  - name: "customTasks"
    type: gitHub
    uri: "https://github.com/Evilazaro/DevExp-DevBox.git"
    branch: "main"
    path: "/.configuration/devcenter/tasks"

# Environment Types section - defines deployment environments for applications
# Each environment type represents a different stage in the development lifecycle
# Best practice: Create environments that match your SDLC stages (dev, test, prod)
environmentTypes:
  - name: "dev"
    deploymentTargetId: "" # Empty for default subscription target
  - name: "staging"
    deploymentTargetId: "" # Empty for default subscription target
  - name: "UAT"
    deploymentTargetId: "" # Empty for default subscription target

# Projects section - defines distinct projects within the Dev Center
# Each project has its own Dev Box configurations, catalogs, and permissions
# Best practice: Create separate projects for different teams or workstreams
projects:
  # Identity Provider project - for authentication/authorization services
  - name: "identityProvider"
    description: "Identity Provider project."

    network:
      name: identityProvider
      create: true
      resourceGroupName: "identityProvider-connectivity-RG"
      virtualNetworkType: Managed
      addressPrefixes:
        - 10.0.0.0/16
      subnets:
        - name: identityProvider-subnet
          properties:
            addressPrefix: 10.0.1.0/24
      tags:
        environment: dev
        division: Platforms
        team: DevExP
        project: DevExP-DevBox
        costCenter: IT
        owner: Contoso
        resources: Network

    # Project identity configuration - controls project-level security
    identity:
      type: SystemAssigned
      roleAssignments:
        - azureADGroupId: "67a29bc3-f25c-4599-9cb1-4da19507e8ee"
          azureADGroupName: "Identity Provider Engineers"
          azureRBACRoles:
            - name: "Contributor"
              id: "b24988ac-6180-42a0-ab88-20f7382dd24c"
              scope: Project
            - name: "Dev Box User"
              id: "45d50f46-0b78-4001-a660-4198cbe8cd05"
              scope: Project
            - name: "Deployment Environment User"
              id: "18e40d4e-8d2e-438d-97e1-9528336e149c"
              scope: Project
            - name: "Key Vault Secrets User"
              id: "4633458b-17de-408a-b874-0445c86b69e6"
              scope: ResourceGroup
            - id: "b86a8fe4-44ce-4948-aee5-eccb2c155cd7"
              name: "Key Vault Secrets Officer"
              scope: ResourceGroup

    # Dev Box pools - collections of Dev Boxes with specific configurations
    # Best practice: Create role-specific pools with appropriate tools and settings
    pools:
      - name: "backend-engineer"
        imageDefinitionName: "identityProvider-backend-engineer"
        vmSku: general_i_32c128gb512ssd_v2
      - name: "frontend-engineer"
        imageDefinitionName: "identityProvider-frontend-engineer"
        vmSku: general_i_16c64gb256ssd_v2

    # Project-specific environment types
    # Defines which deployment environments are available to the project
    environmentTypes:
      - name: "dev"
        deploymentTargetId: ""
      - name: "staging"
        deploymentTargetId: ""

    # Project-specific catalogs - repositories containing project configurations
    catalogs:
      environmentDefinition:
        name: "environments"
        type: gitHub
        uri: "https://github.com/Evilazaro/IdentityProvider.git"
        branch: "main"
        path: "/.configuration/devcenter/environments"
      imageDefinition:
        name: "imageDefinitions"
        type: gitHub
        uri: "https://github.com/Evilazaro/IdentityProvider.git"
        branch: "main"
        path: "/.configuration/devcenter/imageDefinitions"

    # Project-specific tags for resource governance and organization
    # Best practice: Apply consistent tags for cost allocation and ownership
    tags:
      environment: "dev" # Identifies the deployment environment
      division: "Platforms" # Organizational division responsible for the project
      team: "DevExP" # Team responsible for implementation
      project: "DevExP-DevBox" # Project name for cost allocation
      costCenter: "IT" # Financial tracking designation
      owner: "Contoso" # Resource ownership
      resources: "Project" # Resource type identifier

  - name: "eShop"
    description: "eShop project."

    # Network configuration for eShop project
    network:
      name: eShop                                 # Name of the virtual network
      create: true                                # Should the network be created?
      resourceGroupName: "eShop-connectivity-RG"  # Resource group for network
      virtualNetworkType: Managed                 # Type of virtual network
      addressPrefixes:
        - 10.0.0.0/16                             # Address space for VNet
      subnets:
        - name: eShop-subnet           # Subnet name
          properties:
            addressPrefix: 10.0.1.0/24            # Subnet address range
      tags:
        environment: dev                          # Deployment environment
        division: Platforms                       # Organizational division
        team: DevExP                              # Team responsible
        project: DevExP-DevBox                    # Project name
        costCenter: IT                            # Cost center for billing
        owner: Contoso                            # Resource owner
        resources: Network                        # Resource type identifier

    # Project identity configuration - controls project-level security
    identity:
      type: SystemAssigned                        # Managed identity type
      roleAssignments:
        - azureADGroupId: "9d42a792-2d74-441d-8bcb-71009371725f" # Azure AD group ID
          azureADGroupName: "eShop Developers"                    # Azure AD group name
          azureRBACRoles:
            - name: "Contributor"                 # RBAC role name
              id: "b24988ac-6180-42a0-ab88-20f7382dd24c" # RBAC role ID
              scope: Project                      # Role scope
            - name: "Dev Box User"
              id: "45d50f46-0b78-4001-a660-4198cbe8cd05"
              scope: Project
            - name: "Deployment Environment User"
              id: "18e40d4e-8d2e-438d-97e1-9528336e149c"
              scope: Project
            - name: "Key Vault Secrets User"
              id: "4633458b-17de-408a-b874-0445c86b69e6"
              scope: ResourceGroup
            - id: "b86a8fe4-44ce-4948-aee5-eccb2c155cd7"
              name: "Key Vault Secrets Officer"
              scope: ResourceGroup

    # Dev Box pools - collections of Dev Boxes with specific configurations
    # Best practice: Create role-specific pools with appropriate tools and settings
    pools:
      - name: "backend-engineer"                  # Pool for backend engineers
        imageDefinitionName: "eShop-backend-engineer" # Image definition for backend
        vmSku: general_i_32c128gb512ssd_v2         # VM SKU for backend pool
      - name: "frontend-engineer"                 # Pool for frontend engineers
        imageDefinitionName: "eShop-frontend-engineer" # Image definition for frontend
        vmSku: general_i_16c64gb256ssd_v2          # VM SKU for frontend pool

    # Project-specific environment types
    # Defines which deployment environments are available to the project
    environmentTypes:
      - name: "dev"                               # Development environment
        deploymentTargetId: ""
      - name: "staging"                           # Staging environment
        deploymentTargetId: ""
      - name: "UAT"                               # User Acceptance Testing environment
        deploymentTargetId: ""

    # Project-specific catalogs - repositories containing project configurations
    catalogs:
      environmentDefinition:
        name: "environments"
        type: gitHub
        uri: "https://github.com/Evilazaro/eShop.git"
        branch: "main"
        path: "/.devcenter/environments"
      imageDefinition:
        name: "imageDefinitions"
        type: gitHub
        uri: "https://github.com/Evilazaro/eShop.git"
        branch: "main"
        path: "/.devcenter/imageDefinitions"

    # Project-specific tags for resource governance and organization
    # Best practice: Apply consistent tags for cost allocation and ownership
    tags:
      environment: "dev" # Identifies the deployment environment
      division: "Platforms" # Organizational division responsible for the project
      team: "DevExP" # Team responsible for implementation
      project: "DevExP-DevBox" # Project name for cost allocation
      costCenter: "IT" # Financial tracking designation
      owner: "Contoso" # Resource ownership
      resources: "Project" # Resource type identifier

# Top-level tags applied to the Dev Center resource
# Best practice: Implement consistent tagging across all Azure resources
# for improved governance, cost management, and operational tracking
tags:
  environment: "dev" # Identifies the deployment environment
  division: "Platforms" # Organizational division responsible for the resource
  team: "DevExP" # Team responsible for implementation
  project: "DevExP-DevBox" # Project name for cost allocation
  costCenter: "IT" # Financial tracking designation
  owner: "Contoso" # Resource ownership
  resources: "DevCenter" # Resource type identifier
