# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: "0.2.0"
  # This DSC configuration installs and configures the following:
  # - Enables Developer Mode on the system.
  # - Configures Git to use the default WAM account for authentication.
  # - Sets up a Dev Drive with ReFS format for development purposes.
  resources:
    # Enable Developer Mode on the system
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: DeveloperMode
      directives:
        description: Enable Developer Mode
        securityContext: elevated
        allowPrerelease: true
      settings:
        ensure: present

    # Configure Git to use the default WAM account
    - resource: PSDscResources/Script
      id: Git.GitCredentialManager
      directives:
        description: Configure Git to use Default WAM account
        securityContext: elevated
        allowPrerelease: true
      settings:
        SetScript: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
          SET GCM_MSAUTH_USEDEFAULTACCOUNT="true"
          git config --global credential.msauthUseDefaultAccount true
        GetScript: return $false
        TestScript: return $false

    # Configure a Dev Drive with ReFS format
    - resource: Disk
      id: DevDrive1
      directives:
        module: StorageDsc
        allowPrerelease: true
        description: Configure Dev Drive with ReFS format
      settings:
        DiskId: "0"
        DiskIdType: "Number"
        DriveLetter: "Z"
        FSLabel: "Dev Drive 1"
        DevDrive: true
        AllowDestructive: true
        FSFormat: "ReFS"
        Size: "50Gb"
