# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: "0.2.0"
  # This DSC configuration installs and configures the following:
  # - Enables Developer Mode on the system.
  # - Configures Git to use the default WAM account for authentication.
  # - Sets up a Dev Drive with ReFS format for development purposes.
  resources:
    # Configure a Dev Drive with ReFS format
    - resource: Disk
      id: DevDrive1
      directives:
        module: StorageDsc
        allowPrerelease: true
        description: Configure Dev Drive with ReFS format
      settings:
        DiskId: "0"
        DiskIdType: "Number"
        DriveLetter: "Z"
        FSLabel: "Dev Drive 1"
        DevDrive: true
        AllowDestructive: true
        FSFormat: "ReFS"
        Size: "50Gb"

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git.Git
      directives:
        description: Install Git using WinGet
        allowPrerelease: true
      settings:
        id: Git.Git
        