# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  configurationVersion: "0.2.0"
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        securityContext: elevated
        allowPrerelease: true
      settings:
        Enable: true
    - resource: PSDscResources/WindowsOptionalFeature
      directives:
        description: Enable Virtual Machine Platform
        securityContext: elevated
        allowPrerelease: true
      settings:
        Enable: true
        FeatureName: VirtualMachinePlatform