# This is a Visual Studio extension installation task for Dev Box.

$schema: 1.0
name: install-vs-extension
description: Installs a Visual Studio extension
author: Microsoft Corporation
command: ".\\Install-VSIXExtension.ps1 -MarketplaceItemName {{marketplaceItemName}}"