trigger: none

pr: none

stages:
- stage: TestLoginToAzure
  jobs:
  - job: TestLoginToAzure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(AZURE_CREDENTIALS)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging in to Azure..."
          az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)