name: DevBox as a Service CI and CD

permissions:
    id-token: write
    
# note
on:
  workflow_dispatch: # Manually trigger the workflow

env:
  location: "westus3"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  Test-Azure-Credentials-And-Login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  Build:
    runs-on: ubuntu-latest
    needs: Test-Azure-Credentials-And-Login
    steps:
      - name: Upgrade Bicep
        run: |
          sudo az bicep upgrade

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Management Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/management/deploy.bicep --outdir ./bicepArtifacts

      - name: Build Network Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/network/deployNetwork.bicep --outdir ./bicepArtifacts

      - name: Build DevCenter Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outdir ./bicepArtifacts

      - name: Upload Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifactsBicep-ARM-Templates
          path: ./artifactsBicep/*.json

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Update Packages and Upgrade Bicep
        run: |
          sudo apt-get update && \
          sudo az bicep upgrade
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Grant execute permissions to the script
        run: chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

      - name: Deploy Landing Zone Resources for ${{ env.solutionName }}
        run: ./src/deploy/bicep/bash/deployResourcesOrganization.sh ${{ env.devBoxResourceGroupName }} ${{ env.networkResourceGroupName }} ${{ env.managementResourceGroupName }} ${{ env.location }}

      - name: Deploy Log Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName:  ${{ env.managementResourceGroupName }}
          template: ./src/deploy/bicep/management/deploy.bicep
          parameters: 'solutionName=${{ env.solutionName }}'
            
      - name: Deploy Network Connectivity Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.networkResourceGroupName }}
          template: ./src/deploy/bicep/network/deployNetwork.bicep
          parameters: 'solutionName=${{ env.solutionName }}' 

      - name: Deploy Dev Center Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.devBoxResourceGroupName }}
          template: ./src/deploy/bicep/devBox/deploy.bicep
          parameters: 'solutionName=${{ env.solutionName }}' 