name: Deploy DevBox as a Service to Azure

permissions:
    id-token: write
    contents: write
    
# note
on:
  workflow_dispatch: # Manually trigger the workflow

env:
  location: "northuscentral"
  solutionName: "PetDx"
  devBoxResourceGroupName: "PetDx-rg"
  networkResourceGroupName: "PetDx-Network-rg"
  managementResourceGroupName: "PetDx-Management-rg"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  Test-Azure-Credentials-And-Login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  Build:
    name: Build Bicep Artifacts
    runs-on: ubuntu-latest
    needs: Test-Azure-Credentials-And-Login
    steps:
      - name: Upgrade Bicep
        run: |
          sudo az bicep upgrade

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Dev Box Management Bicep files
        run: az bicep build --file ./src/deploy/bicep/management/logAnalytics/deploy.bicep --outfile ./bicepArtifacts/deployManagement.json

      - name: Build Dev Box Network Bicep files
        run: az bicep build --file ./src/deploy/bicep/network/deploy.bicep --outfile ./bicepArtifacts/deployNetwork.json

      - name: Build Dev Box DevCenter Bicep files
        run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./bicepArtifacts/deployDevBox.json

      - name: Compress Bicep Artifacts
        run: |
          zip -r bicepArtifacts_v1.0.0-deploy-${{ github.run_number }}.zip ./bicepArtifacts

      - name: Upload Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bicepArtifacts_v1.0.0-deploy-${{ github.run_number }}.zip
          path: bicepArtifacts_v1.0.0-deploy-${{ github.run_number }}.zip

  Deploy:
    name: Deploy Dev Box Resources to Azure
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Update Packages and Upgrade Bicep
        run: |
          sudo apt-get update && \
          sudo az bicep upgrade
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Grant execute permissions to the script
        run: chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

      - name: Deploy Landing Zone Resources for ${{ env.solutionName }}
        run: ./src/deploy/bicep/bash/deployResourcesOrganization.sh ${{ env.devBoxResourceGroupName }} ${{ env.networkResourceGroupName }} ${{ env.managementResourceGroupName }} ${{ env.location }}
      
      - name: Deploy Log Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName:  ${{ env.managementResourceGroupName }}
          template: ./src/deploy/bicep/management/logAnalytics/deploy.bicep
          parameters: 'solutionName=${{ env.solutionName }}'
      
      - name: Deploy Network Connectivity Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.networkResourceGroupName }}
          template: ./src/deploy/bicep/network/deploy.bicep
          parameters: 'solutionName=${{ env.solutionName }} managementResourceGroupName=${{ env.managementResourceGroupName }}'

      - name: Deploy Dev Center Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.devBoxResourceGroupName }}
          template: ./src/deploy/bicep/devBox/deploy.bicep
          parameters: 'solutionName=${{ env.solutionName }} managementResourceGroupName=${{ env.managementResourceGroupName }}'

  publish-bicep-artifacts:
      runs-on: ubuntu-latest
      needs: Build
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Bicep Artifacts
        uses: actions/download-artifact@v4
        with:
          name: bicepArtifacts_v1.0.0-deploy-${{ github.run_number }}.zip

      - name: Upload Bicep Artifacts to Storage
        run: |
          # Add your upload logic here
          echo "Uploading Bicep artifacts"