name: Deploy DevBox as a Service to Azure

on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - main


env:
  location: "WestUS3"

  # Azure Resource Group Names Constants
  devBoxResourceGroupName: "eShopPetDevBox-rg"
  networkResourceGroupName: "eShopPetNetworkConnectivity-rg"
  managementResourceGroupName: "eShopPetDevBoxManagement-rg"

  # Identity Parameters Constants
  identityName: "eShopPetDevBoxImgBldId"
  customRoleName: "eShopPetBuilderRole"

  # Image and DevCenter Parameters Constants
  computeGalleryName: "eShopPetImageGallery"
  devCenterName: "eShopPetDevCenter"

  # Network Parameters Constants
  vnetName: "eShopPetVnet"
  subNetName: "eShopPetSubNet"
  networkConnectionName: "eShopPetNetworkConnection"
  
  # Management Parameters constants
  logAnalyticsWorkspaceName: "eShopPetDevBoxLogAnalytics"

jobs:
    Deploy-DevBox-As-A-Service-For-eShop:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Log in to Azure
            uses: azure/login@v2
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Bicep Upgrade
            run: az bicep upgrade

          - name: Give execute permissions to the script
            run: chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

          - name: Create Resources Organization
            run: ./src/deploy/bicep/bash/deployResourcesOrganization.sh

          - name: Deploy Log Analytics
            uses: azure/arm-deploy@v1
            with:
              subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
              resourceGroupName: ${{ env.managementResourceGroupName }}
              template: ./src/deploy/bicep/management/deploy.bicep
              parameters: |
                logAnalyticsWorkspaceName=${{ env.logAnalyticsWorkspaceName }}

          - name: Deploy Network Connectivity Resources
            uses: azure/arm-deploy@v1
            with:
              subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
              resourceGroupName: ${{ env.networkResourceGroupName }}
              template: ./src/deploy/bicep/network/deploy.bicep
              parameters: |
                vnetName=${{ env.vnetName }}
                subNetName=${{ env.subNetName }}
                networkConnectionName=${{ env.networkConnectionName }}
                logAnalyticsWorkspaceName=${{ env.logAnalyticsWorkspaceName }}
                managementResourceGroupName=${{ env.managementResourceGroupName }}