name: Deploy DevBox as a Service to Azure

on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # - name: Deploy Bicep script
        #   uses: azure/arm-deploy@v1
        #   with:
        #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #     resourceGroupName: myResourceGroup
        #     template: ./path/to/your/template.bicep
        #     parameters: |
        #         parameter1=${{ secrets.PARAMETER1 }}
        #         parameter2=${{ secrets.PARAMETER2 }}

