name: Build and Deploy DevBox as a Service for eShop

permissions:
    id-token: write
    
# note
on:
  workflow_dispatch: # Manually trigger the workflow

env:
  location: "WestUS3"

  # Azure Resource Group Names Constants
  devBoxResourceGroupName: "eShopPetDevBox-rg"
  networkResourceGroupName: "eShopPetNetworkConnectivity-rg"
  managementResourceGroupName: "eShopPetDevBoxManagement-rg"

  # Identity Parameters Constants
  identityName: "eShopPetDevBoxImgBldId"
  customRoleName: "eShopPetBuilderRole"

  # Image and DevCenter Parameters Constants
  computeGalleryName: "eShopPetImageGallery"
  devCenterName: "eShopPetDevCenter"

  # Network Parameters Constants
  vnetName: "eShopPetVnet"
  subNetName: "eShopPetSubNet"
  networkConnectionName: "eShopPetNetworkConnection"

  # Management Parameters constants
  logAnalyticsWorkspaceName: "eShopPetDevBoxLogAnalytics"

jobs:
  Build-And-Deploy-DevBox-As-A-Service-For-eShop:
    runs-on: ubuntu-latest

    steps:
      - name: Update Packages
        run: |
          sudo apt-get update && \
          sudo apt-get upgrade -y

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bicep Upgrade
        run: az bicep upgrade

      - name: Validate Management Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/management/deploy.bicep --outfile ./artifactsBicep/management.json

      - name: Validate Network Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/network/deploy.bicep --outfile ./artifactsBicep/network.json

      - name: Validate DevCenter Bicep Templates
        run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./artifactsBicep/devBox.json

      - name: Upload Bicep Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifactsBicep-ARM-Templates
          path: ./artifactsBicep/*.json

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Bicep Upgrade
        run: az bicep upgrade

      - name: Give execute permissions to the script
        run: chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

      - name: Create Resources Organization
        run: ./src/deploy/bicep/bash/deployResourcesOrganization.sh

      - name: Deploy Log Analytics
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.managementResourceGroupName }}
          template: ./src/deploy/bicep/management/deploy.bicep
          parameters: |
            logAnalyticsWorkspaceName=${{ env.logAnalyticsWorkspaceName }}
            
      - name: Deploy Network Connectivity Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.networkResourceGroupName }}
          template: ./src/deploy/bicep/network/deploy.bicep
          parameters: 'vnetName=${{ env.vnetName }} subnetName=${{ env.subNetName }} networkConnectionName=${{ env.networkConnectionName }} logAnalyticsWorkspaceName=${{ env.logAnalyticsWorkspaceName }} managementResourceGroupName=${{ env.managementResourceGroupName }}' 

      - name: Deploy DevCenter Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId}}
          resourceGroupName: ${{ env.devBoxResourceGroupName }}
          template: ./src/deploy/bicep/devBox/deploy.bicep
          parameters: 'devCenterName=${{ env.devCenterName }} networkConnectionName=${{ env.networkConnectionName }} identityName=${{ env.identityName }} customRoleName=${{ env.customRoleName }} computeGalleryName=${{ env.computeGalleryName }} networkResourceGroupName=${{ env.networkResourceGroupName }} currentUser=f7d97159-e451-49e7-8b8c-83e0dc73597e logAnalyticsWorkspaceName=${{ env.logAnalyticsWorkspaceName }} managementResourceGroupName=${{ env.managementResourceGroupName }}'