name: Deploy DevBox as a Service to Azure

on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - main

jobs:
    Deploy-DevBox-To-Azure:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Log in to Azure
            uses: azure/login@v2
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Give execute permissions to the script
            run: chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

          - name: Create Resources Organization
            run: ./src/deploy/bicep/bash/deployResourcesOrganization.sh
