name: DevBox as a Service Continuous Integration

permissions:
    id-token: write
# note
on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - main

jobs:
    Validate-and-Build-Bicep-Templates:
      runs-on: ubuntu-latest
      steps:
        - name: Update Packages and Upgrade Bicep
          run: |
            sudo apt-get update && \
            sudo apt-get upgrade -y \
            sudo az bicep upgrade

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Validate Management Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/management/deploy.bicep --outfile ./artifactsBicep/deployManagement.json

        - name: Validate Network Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/network/deploy.bicep --outfile ./artifactsBicep/deployNetwork.json

        - name: Validate DevCenter Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./artifactsBicep/deployDevBox.json

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifactsBicep-ARM-Templates
            path: ./artifactsBicep/*.json