name: DevBox as a Service CI

permissions:
  id-token: write

# Trigger the workflow manually or on push to specific branches
on:
  workflow_dispatch: # Manually trigger the workflow
  push:
    branches:
      - 'feature/**' # Branches containing feature/ in the name
      - 'bugfix/**' # Branches containing bugfix/ in the name
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Upgrade Bicep to the latest version
      - name: Upgrade Bicep
        run: |
          sudo apt-get update && \
          sudo apt-get upgrade -y && \
          sudo az bicep upgrade

      # Checkout the repository to get the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the Bicep files for Dev Box Resources
      - name: Build Dev Box Bicep files
        run: az bicep build --file ./src/bicep/deploy.bicep --outfile ./bicepArtifacts/deploy.json

      # Compress the built Bicep artifacts into a zip file
      - name: Compress Bicep Artifacts
        run: |
          zip -r bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip ./bicepArtifacts

      # Upload the compressed Bicep artifacts
      - name: Upload Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip
          path: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip