name: DevBox as a Service Continuous Deployment

permissions:
    id-token: write
# note
on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - main

jobs:
    Validate-and-Build-Bicep-Templates:
      runs-on: ubuntu-latest
      steps:
        - name: Update Bicep
          run: |
            sudo az bicep upgrade

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Validate Management Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/management/deploy.bicep --outfile ./artifactsBicep/deployManagement.json

        - name: Validate Network Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/network/deploy.bicep --outfile ./artifactsBicep/deployNetwork.json

        - name: Validate DevCenter Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./artifactsBicep/deployDevBox.json

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifactsBicep-ARM-Templates
            path: ./artifactsBicep/*.json
      
        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: "${{ github.run_number }}-GA"  
            release_name: "Release ${{ github.ref_name }}"
            body: |
              Release notes for ${{ github.ref_name }}.
            draft: false
            prerelease: false

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./releases
            asset_name: devBox-CD
            asset_content_type: application/zip