name: DevBox as a Service CI

permissions:
    id-token: write
# note
on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - 'feature/**' # Branches containing feature/ in the name
            - 'bugfix/**' # Branches containing bugfix/ in the name
            - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Upgrade Bicep
          run: |
            sudo az bicep upgrade

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build Management Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/management/logAnalytics/deploy.bicep --outdir ./bicepArtifacts  

        - name: Build Network Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/network/deployNetwork.bicep --outdir ./bicepArtifacts

        - name: Build DevCenter Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outdir ./bicepArtifacts        

        - name: Compress Bicep Artifacts
          run: |
            zip -r bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip ./bicepArtifacts

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip
            path: bicepArtifacts_v1.0.0-build-${{ github.run_number }}.zip