name: DevBox as a Service CI

permissions:
    id-token: write
# note
on:
    workflow_dispatch: # Manually trigger the workflow
    push:
        branches:
            - 'feature/**' # Branches containing feature/ in the name
            - 'bugfix/**' # Branches containing bugfix/ in the name
            - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
    Validate-and-Build-Bicep-Templates:
      runs-on: ubuntu-latest
      steps:
        - name: Update Bicep
          run: |
            sudo az bicep upgrade

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build Management Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/management/deploy.bicep --outfile ./artifactsBicep/deployManagement.json

        - name: Build Network Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/network/deployNetwork.bicep --outfile ./artifactsBicep/deployNetwork.json

        - name: Build DevCenter Bicep Templates
          run: az bicep build --file ./src/deploy/bicep/devBox/deploy.bicep --outfile ./artifactsBicep/deployDevBox.json

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifactsBicep-ARM-Templates
            path: ./artifactsBicep/*.json