name: Test Login To Azure

on: 
    workflow_dispatch: # Manually trigger the workflow

permissions:
    id-token: write

jobs:
  testLoginToAzure:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}