$schema: "1.0"
name: "devbox-backend-customization"
description: "Customize the backend workload for the devbox"
tasks:
  - name: winget
    description: "Install Windows Subsystem for Linux"
    parameters:
        package: Microsoft.WSL
  - name: powershell
    description: "Install Visual Studio Code"
    parameters:
        command: "winget install -e --id Microsoft.VisualStudioCode --source winget --accept-source-agreements --accept-package-agreements --silent --force"
  - name: powershell
    description: "Update winget packages"
    parameters:
        command: "winget upgrade --all -e --accept-source-agreements --accept-package-agreements --silent --force"