$schema: "1.0"
name: "devbox-backend-customization"
description: "Customize the backend workload for the devbox"
tasks:
  - name: install-winget
    description: Install Windows Package Manager (winget)
  - name: install-wsl
    description: Install Windows Subsystem for Linux (WSL)
  - name: git-clone
    description: Cloning the Microsoft DevBox repository
    parameters:
      repositoryUrl: https://github.com/Evilazaro/MicrosoftDevBox
  - name: git-clone
    description: Cloning the eShop on Containers repository
    parameters:
      repositoryUrl: https://github.com/Evilazaro/eShopOnContainers